// ForgeNote M1 — UI copy 资源（en，scaffold）。与 zh-Hans 同一组 key（`Copy` 类型编译期强制一致）。
// 英文为合理 scaffold，未做产品级润色。当前默认语言为 zh-Hans；本文件仅脚手架，不在运行时启用。

import type { Copy } from "./zh-Hans";

export const en: Copy = {
  common: {
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    edit: "Edit",
    delete: "Delete",
    confirmDeletePrompt: "Delete?",
    confirmDelete: "Confirm delete",
    deleting: "Deleting…",
    copied: "Copied",
    networkError: "Network error, please try again.",
    optionalSuffix: " (optional)",
  },
  nav: {
    forge: "Forge",
    recipes: "Recipes",
    profile: "Preferences",
    signOut: "Sign out",
    signOutTitle: "Sign out",
  },
  intentTypes: {
    content_package: "Content plan",
    xiaohongshu_note: "Visual note",
    card_prompt: "Visual brief",
    generic_content: "Generic content",
    all: "All types",
  },
  login: {
    googleButton: "Continue with Google",
    emailDivider: "or use email",
    sendMagicLink: "Send login link",
    sending: "Sending…",
    footerNote: "Sign in to save recipes and preferences.",
    notConfiguredTitle: "Sign-in unavailable: Supabase not configured",
    notConfiguredBody:
      "Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY; please set them in the environment and retry.",
    googleUnavailable: "Google sign-in is unavailable; please use the email magic link instead.",
    googleInitFailed: "Could not start Google sign-in; please retry or use email.",
    magicSendFailed: "Failed to send, please try again.",
    magicSendNetworkError: "Failed to send; check your network and retry.",
    emailLabel: "Email address",
    emailPlaceholder: "you@example.com",
    magicSentTitle: "Login link sent",
    magicSentBodyPrefix: "We sent a login email to ",
    magicSentBodySuffix: " — click the link in it to sign in.",
    changeEmail: "Use a different email",
  },
  idea: {
    kicker: "Start from an idea",
    title: "Turn a rough thought into a content plan you can start from",
    inputAria: "Idea input",
    tooLong: "Over {max} characters, please shorten before forging",
    counter: "{count} / {max}",
    forge: "Generate content plan",
    forging: "Generating…",
    examplesHint: "Try these examples:",
    savedAt: "Autosaved {time}",
    accountPostToggle: "For a better fit, paste one previous post",
    accountPostAria: "Previous post input",
    accountPostPlaceholder:
      "Paste one piece you have posted before. It is only used for this run to infer audience, angle, and account voice.",
    accountPostTooLong: "Previous post is over {max} characters; please shorten it",
  },
  forge: {
    outputLocaleLabel: "Output language / tone",
    outputLocalePlaceholder: "e.g. zh-Hans, en-US, English for Instagram carousel",
    generateFailed: "Generation failed, please try again",
  },
  shell: {
    drafting: "Drafting this idea",
    reviewing: "Confirm the direction first",
    generating: "Generating content plan",
    generated: "Content plan generated",
    error: "Generation needs attention",
  },
  direction: {
    ready: "Direction pending",
    title: "I drafted the direction first. Fix what feels off.",
    summaryWithPost:
      "This run uses your input and previous post to clarify whether to save, how much, where it lives, and when it can move.",
    summaryWithoutPost:
      "This run starts from a common-reader assumption to clarify whether to save, how much, where it lives, and when it can move.",
    confirmed: "{n}/3 confirmed",
    defaultNotice: "Unchanged items use the default read",
    rationale: "Why",
    noRationale: "No further rationale for this direction yet.",
    remember: "Remember",
    generate: "Generate content plan",
  },
  outcome: {
    loading: "Forging content…",
    authRequiredTitle: "Sign in to generate",
    authRequiredBody: "Please sign in before forging.",
    failTitle: "Generation failed",
    failBody: "Generation failed, please try again.",
    sessionLabel: "session: ",
    localeLabel: "Output language / tone: ",
    copyAll: "Copy all",
    copyBody: "Copy body",
    copyPrompts: "Copy visual briefs",
    copyTags: "Copy hashtags",
    regenerate: "Regenerate",
    new: "New",
    positioning: "Positioning",
    titles: "Title options",
    body: "Body",
    cardStructure: "Card structure",
    cardPrompts: "Visual briefs",
    hashtags: "Hashtags",
    commentGuide: "Comment prompt",
    cardNo: "Card {n}",
    cardNoBracket: "[Card {n}]",
    emptyTitle: "Your generated result will appear here",
    emptyBody:
      "Enter an idea and click “Generate content plan” to generate titles, body, visual briefs, and hashtags.",
  },
  recipePanel: {
    loading: "Organizing recipe…",
    copySummary: "Copy recipe summary",
    saveRecipe: "Save recipe",
    saved: "Saved to recipes",
    needSession: "Generate content successfully first",
    namePlaceholder: "Name this recipe",
    nameAria: "Recipe name",
    saveFailed: "Failed to save, please try again",
    verificationTitle: "Checks",
    verifyPass: "All passed",
    verifyFail: "Some checks failed",
    emptyTitle: "Your content recipe will appear here",
    emptyBody: "A recipe records how this content was generated, so you can rerun with new input.",
    summaryName: "Recipe name",
    summaryIntent: "Content type",
    summaryAudience: "Audience",
    summaryGoal: "Goal",
    summaryTone: "Tone",
    summaryVisual: "Visual style",
    summaryStructure: "Structure",
    summaryNegative: "Negative rules",
    summaryVariables: "Variables",
    summaryAcceptance: "Acceptance",
  },
  assumptions: {
    title: "Assumptions",
    hint: "These are how the system understands your idea. Click to edit, × to remove, then click “Apply and regenerate”.",
    regenerate: "Apply changes and regenerate",
    edited: "Edited",
    fromProfile: "From preferences",
    remembered: "Remembered",
    rememberTitle: "Remember as a preference, auto-applied next time",
    editTitle: "Click to edit",
    restoreTitle: "Click to restore",
    allDismissed: "All assumptions removed; generation will use only the raw input.",
    dismissedLabel: "Removed assumptions ({n})",
    restoreAll: "Restore all",
    editAria: "Edit {label}",
    rememberAria: "Remember “{label}” as a preference",
    dismissAria: "Remove assumption {label}",
  },
  performance: {
    expand: "Record performance",
    title: "Record performance",
    subtitle: "Manual entry, visible only to you, never auto-fetched",
    unfilled: "Unset",
    rangeSuffix: " range",
    publishedAt: "Published at (optional)",
    note: "One-line recap (optional)",
    notePlaceholder: "e.g. saves outpaced likes; how-to content worked",
    save: "Save performance",
    saving: "Saving…",
    saved: "Performance recorded",
    failed: "Failed to save, please try again",
    like: "Likes",
    favorite: "Saves",
    comment: "Comments",
    follower: "Followers",
  },
  recipes: {
    title: "Recipes",
    description: "Browse, search, filter, and delete your saved content recipes.",
    newRecipe: "New recipe",
    searchAria: "Search recipe names",
    searchPlaceholder: "Search by recipe name",
    filterAria: "Filter by content type",
    search: "Search",
    filtering: "Filtering…",
    clear: "Clear",
    showing: "Showing {n}",
    ofTotal: " / {n} total",
    loadingResults: "Loading results…",
    deleted: "Recipe deleted",
    deleteFailed: "Failed to delete, please try again",
    createdAt: "Created",
    updatedAt: "Updated",
    usageCount: "Uses",
    sourceSession: "Source session",
    noSource: "No source session",
    viewDetail: "View details",
    emptyFilteredTitle: "No matching recipes",
    emptyTitle: "No recipes yet",
    emptyFilteredBody: "Try a different keyword or content type.",
    emptyBody: "Generate content in the Forge workbench, then save useful recipes here.",
    goCreate: "Create in Forge",
  },
  recipeDetail: {
    backToLibrary: "Back to recipes",
    fieldsTitle: "Recipe fields",
    rerunTitle: "Rerun with new input",
    notFoundTitle: "Recipe not found or not visible",
    notFoundBody: "This recipe may have been deleted, or it doesn't belong to your account.",
    backToLibraryBtn: "Back to recipes",
    createdAt: "Created",
    updatedAt: "Updated",
    usageCount: "Uses",
    sourceSession: "Source session",
    noSource: "No source session",
    audience: "Audience",
    goal: "Goal",
    tone: "Tone",
    visualStyle: "Visual style",
    structure: "Structure",
    variables: "Variables",
    negativeRules: "Negative rules",
    acceptance: "Acceptance",
    schema: "Version",
    rerunDescription:
      "Reuse this recipe with a new topic to generate a fresh result. The original recipe is unchanged.",
    rerunPlaceholder: "Write a new topic, e.g. a move-out photo checklist carousel",
    rerunButton: "Rerun with new input",
    rerunning: "Rerunning…",
    charCounter: "{count} / {max} chars",
    overLimitSuffix: " (over limit)",
    rerunFailed: "Rerun failed, please try again",
  },
  profile: {
    title: "Preferences",
    description:
      "Remember the content assumptions you use often (audience, tone, visual style, etc.). They are carried into the next Forge generation as assumptions, and you can edit or delete them anytime.",
    addTitle: "Add preference",
    intentTypeAria: "Content type",
    dimensionLabelPlaceholder: "Dimension name, e.g. Tone",
    dimensionKeyPlaceholder: "Dimension key, e.g. tone",
    add: "Add",
    valuePlaceholder: "Preference value, e.g. mature, restrained, calm",
    addHint:
      "Re-adding the same “content type + dimension key” overwrites the old value. Carried into the next Forge generation as a “from preferences” assumption.",
    count: "{n} preferences",
    refreshing: "Refreshing…",
    savedPref: "Preference saved",
    updatedPref: "Preference updated",
    deletedPref: "Preference deleted",
    saveFailed: "Failed to save, please try again",
    editFailed: "Failed to update, please try again",
    deleteFailed: "Failed to delete, please try again",
    editValueAria: "Edit the value of {label}",
    updatedAt: "Updated {date}",
    emptyTitle: "No preferences yet",
    emptyBody:
      "Add common content assumptions above, or click “Remember as preference” after editing an assumption in the Forge workbench. They'll be applied to the next generation.",
  },
};
