// ForgeNote M2 — UI copy resource (en scaffold). Same keys as zh-Hans (`Copy` enforces this).
// 英文为合理 scaffold，未做产品级润色。当前默认语言为 zh-Hans；本文件仅脚手架，不在运行时启用。

import type { Copy } from "./zh-Hans";

export const en: Copy = {
  common: {
    cancel: "Cancel",
    save: "Save",
    saving: "Saving…",
    edit: "Edit",
    delete: "Delete",
    confirmDeletePrompt: "Delete?",
    confirmDelete: "Confirm delete",
    deleting: "Deleting…",
    copied: "Copied",
    networkError: "Network error, please try again.",
    optionalSuffix: " (optional)",
  },
  nav: {
    profile: "Preferences",
    signOut: "Sign out",
    signOutTitle: "Sign out",
  },
  intentTypes: {
    content_package: "Content plan",
    xiaohongshu_note: "Visual note",
    card_prompt: "Visual brief",
    generic_content: "Generic content",
    all: "All types",
  },
  login: {
    categoryLine: "Visual card content studio",
    signinTitle: "Welcome back",
    signinSubtitle: "Enter your email and password to keep forging",
    signupTitle: "Create account",
    signupSubtitle: "Add an email and password to start using ForgeNote",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter password",
    passwordPlaceholderSignup: "Set a password (min 8 chars)",
    confirmPasswordLabel: "Confirm password",
    confirmPasswordPlaceholder: "Confirm password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    rememberFor30Days: "Stay signed in for 30 days",
    forgotPassword: "Forgot password?",
    submit: "Sign in",
    submitting: "Signing in…",
    signupSubmit: "Create account",
    google: "Continue with Google",
    googleRedirecting: "Redirecting to Google…",
    orDivider: "or",
    noAccountPrompt: "No account yet?",
    toSignUpLink: "Create one",
    hasAccountPrompt: "Already have an account?",
    toSignInLink: "Back to sign in",
    invalidCredentials:
      "Email or password is incorrect. Please check and try again.",
    emailNotConfirmed:
      "This email is not confirmed yet. Confirm it once, then sign in with your password.",
    authNeedsCheck:
      "Sign-in did not complete. Check your email, password, or confirmation email.",
    authFailed: "Sign-in failed. Please try again.",
    networkError: "Sign-in failed. Check your network and retry.",
    googleUnavailable:
      "Google sign-in is unavailable; please use email and password instead.",
    googleInitFailed: "Could not start Google sign-in; please retry or use email.",
    signupSentTitle: "Confirmation email sent",
    signupSentBodyPrefix: "We've sent a confirmation email to ",
    signupSentBodySuffix:
      ". Confirm once, then sign in with email and password.",
    changeEmail: "Use a different email",
    notConfiguredTitle: "Sign-in unavailable: Supabase not configured",
    notConfiguredBody:
      "Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY. Set them in your environment and retry.",
  },
  reset: {
    requestTitle: "Reset password",
    requestSubtitle: "Enter your account email and we'll send a reset link",
    submit: "Send reset email",
    submitting: "Sending…",
    backToSignIn: "← Back to sign in",
    sentTitle: "Reset email sent",
    sentBodyPrefix: "We've sent a reset link to ",
    sentBodySuffix: ". Open it and follow the link to set a new password.",
    resend: "Didn't get it? Resend",
    resendIn: "Resend in {seconds}s",
    cooldownHint:
      "Check the newest email first. To avoid duplicate messages, you can resend in {seconds}s.",
    canResendHint: "If it still has not arrived, send one fresh reset email.",
    newTitle: "Set a new password",
    newSubtitle: "Choose a new password for your account (min 8 chars)",
    newPasswordPlaceholder: "New password (min 8 chars)",
    confirmPasswordPlaceholder: "Re-enter new password",
    saveNewPassword: "Save new password",
    saving: "Saving…",
    passwordMismatch: "The two passwords don't match.",
    sendFailed: "The email was not sent. Check the newest email first, then resend later.",
    updateFailed: "Reset failed. Please start password recovery again.",
    networkError: "Something went wrong. Check your network and retry.",
    linkInvalid: "This reset link is invalid or expired. Please request a new one.",
    doneTitle: "Password updated",
    doneBody: "Your new password is set — you can sign in with it now.",
    goSignIn: "Go to sign in",
  },
  performance: {
    expand: "Record performance",
    title: "Record performance",
    subtitle: "Manual entry, visible only to you, never auto-fetched",
    unfilled: "Unset",
    rangeSuffix: " range",
    publishedAt: "Published at (optional)",
    note: "One-line recap (optional)",
    notePlaceholder: "e.g. saves outpaced likes; how-to content worked",
    save: "Save performance",
    saving: "Saving…",
    saved: "Performance recorded",
    failed: "Failed to save, please try again",
    like: "Likes",
    favorite: "Saves",
    comment: "Comments",
    follower: "Followers",
  },
  profile: {
    title: "Preferences",
    description:
      "Remember the content assumptions you use often (audience, tone, visual style, etc.). They are carried into the next workspace generation as assumptions, and you can edit or delete them anytime.",
    addTitle: "Add preference",
    intentTypeAria: "Content type",
    dimensionLabelPlaceholder: "Dimension name, e.g. Tone",
    dimensionKeyPlaceholder: "Dimension key, e.g. tone",
    add: "Add",
    valuePlaceholder: "Preference value, e.g. mature, restrained, calm",
    addHint:
      "Re-adding the same content type and dimension key overwrites the old value. Carried into the next workspace generation as a from-preferences assumption.",
    count: "{n} preferences",
    refreshing: "Refreshing…",
    savedPref: "Preference saved",
    updatedPref: "Preference updated",
    deletedPref: "Preference deleted",
    saveFailed: "Failed to save, please try again",
    editFailed: "Failed to update, please try again",
    deleteFailed: "Failed to delete, please try again",
    editValueAria: "Edit the value of {label}",
    updatedAt: "Updated {date}",
    emptyTitle: "No preferences yet",
    emptyBody:
      "Add common content assumptions above, or click Remember as preference after editing an assumption in the workspace. They will be applied to the next generation.",
  },
};
