// ForgeNote M1 — UI copy 资源（zh-Hans，**规范源**）。I-17 起脚手架，I-18 补齐活跃页面覆盖。
//
// 设计：
//   - 本文件是 copy 的**唯一规范结构**与默认语言；值为当前线上中文文案，逐字迁移、不改产品含义。
//   - `Copy = typeof zhHans`（不使用 `as const`，值类型收敛为 string）→ `en` 必须实现同一组 key，
//     从而在编译期保证两套 copy **key 不漂移**（缺 key / 多 key / 改 key 都会类型报错）。
//   - 仅 scaffold：不引入 i18n 运行时 / 不做语言切换 / 默认仍 zh-Hans，行为不变。
//   - 含 `{n}` / `{max}` / `{label}` / `{date}` 占位符的值，由调用处 `.replace(...)` 注入。
//   - 已在 `constants.ts` 集中的产品级文案（PRODUCT_NAME / SLOGAN / POSITIONING / 示例想法 / 输入占位）
//     不在此重复，避免双源漂移。

export const zhHans = {
  common: {
    cancel: "取消",
    save: "保存",
    saving: "保存中…",
    edit: "编辑",
    delete: "删除",
    confirmDeletePrompt: "确认删除？",
    confirmDelete: "确认删除",
    deleting: "删除中…",
    copied: "已复制",
    networkError: "网络异常，请稍后重试",
    optionalSuffix: "（可选）",
  },
  nav: {
    forge: "Forge",
    recipes: "配方库",
    profile: "偏好",
    signOut: "退出",
    signOutTitle: "退出登录",
  },
  intentTypes: {
    content_package: "内容方案",
    xiaohongshu_note: "图文笔记",
    card_prompt: "画面说明",
    generic_content: "通用内容",
    all: "全部类型",
  },
  login: {
    googleButton: "使用 Google 登录",
    emailDivider: "或使用邮箱",
    sendMagicLink: "发送登录链接",
    sending: "发送中…",
    footerNote: "登录后可保存配方和偏好。",
    notConfiguredTitle: "登录暂不可用：Supabase 未配置",
    notConfiguredBody:
      "缺少 NEXT_PUBLIC_SUPABASE_URL 或 NEXT_PUBLIC_SUPABASE_ANON_KEY，请在环境变量中配置后重试。",
    googleUnavailable: "Google 登录暂不可用，请改用邮箱 Magic Link 登录。",
    googleInitFailed: "无法发起 Google 登录，请稍后重试或改用邮箱登录。",
    magicSendFailed: "发送失败，请稍后重试。",
    magicSendNetworkError: "发送失败，请检查网络后重试。",
    emailLabel: "邮箱地址",
    emailPlaceholder: "you@example.com",
    magicSentTitle: "登录链接已发送",
    magicSentBodyPrefix: "我们已向 ",
    magicSentBodySuffix: " 发送了一封登录邮件，点击其中的链接即可登录。",
    changeEmail: "换一个邮箱",
  },
  idea: {
    kicker: "从想法开始",
    title: "把一个模糊想法，变成可以直接开始做的内容方案",
    inputAria: "想法输入",
    tooLong: "已超过 {max} 字，请精简后再锻造",
    counter: "{count} / {max}",
    forge: "先确认方向",
    forging: "生成中…",
    examplesHint: "试试这些示例：",
    savedAt: "已自动保存 {time}",
    accountPostToggle: "想更准？贴一条你发过的帖",
    accountPostAria: "过往帖输入",
    accountPostPlaceholder:
      "粘贴一条你发过的内容。它只用于本次判断受众、表达角度和账号语气。",
    accountPostTooLong: "过往帖已超过 {max} 字，请精简后再继续",
  },
  forge: {
    outputLocaleLabel: "输出语言 / 表达偏好",
    outputLocaleHint: "不选也可以。选择后会按这个语言或表达场景生成。",
    outputLocalePlaceholder: "例如：zh-Hans、en-US、English for Instagram carousel",
    outputLocalePresetZh: "中文",
    outputLocalePresetEn: "English",
    outputLocalePresetInstagram: "Instagram carousel",
    outputLocalePresetLinkedIn: "LinkedIn carousel",
    outputLocaleClear: "清空",
    generateFailed: "生成失败，请重试",
  },
  shell: {
    drafting: "输入一个想法开始",
    reviewing: "先确认方向，再生成",
    generating: "正在生成内容方案",
    generated: "内容方案已生成",
    error: "生成遇到问题",
  },
  direction: {
    ready: "方向待确认",
    title: "我先帮你定了这次的方向，改不对的就行",
    summaryWithPost:
      "这次我会参考你的输入和过往帖，替你讲清：要不要存、存多少、放在哪、什么时候能动。",
    summaryWithoutPost:
      "这次我会先按常见读者理解，替你讲清：要不要存、存多少、放在哪、什么时候能动。",
    confirmed: "已确认 {n}/3",
    defaultNotice: "没改的我按默认理解来",
    rationale: "依据",
    noRationale: "这条方向暂无更多依据。",
    remember: "记住",
    generate: "生成内容方案",
  },
  outcome: {
    loading: "正在锻造内容…",
    authRequiredTitle: "需要登录后才能生成",
    authRequiredBody: "请登录后再开始锻造。",
    failTitle: "生成失败",
    failBody: "生成失败，请重试。",
    sessionLabel: "session：",
    localeLabel: "输出语言 / 表达偏好：",
    copyAll: "复制全文",
    copyBody: "复制正文",
    copyPrompts: "复制逐页卡片文案",
    copyTags: "复制话题",
    regenerate: "重新生成",
    new: "新建",
    positioning: "内容定位",
    titles: "标题备选",
    body: "发布正文",
    cardStructure: "卡片结构",
    cardPrompts: "逐页卡片文案",
    visualDirections: "配图方向",
    publishChecklist: "发布前检查",
    hashtags: "发布话题",
    commentGuide: "评论区引导",
    cardNo: "第 {n} 张",
    cardNoBracket: "【第 {n} 张】",
    emptyTitle: "生成结果会出现在这里",
    emptyBody: "输入想法并点击“生成内容方案”后，将生成标题、正文、画面说明和话题。",
  },
  recipePanel: {
    loading: "正在整理配方…",
    saveValueTitle: "保存前先判断：这次配方值不值得留",
    saveValueBody:
      "保存后会复用这次的受众、目标、语气和结构方式。只保存你愿意下次继续沿用的判断。",
    copySummary: "复制配方摘要",
    saveRecipe: "保存配方",
    saved: "已保存到配方库",
    viewRecipe: "查看配方",
    savedReuseHint: "下一步去配方详情换一个输入重跑，确认这个判断真的能复用。",
    needSession: "需要先成功生成内容",
    namePlaceholder: "给这个配方起个名字",
    nameAria: "配方名称",
    saveFailed: "保存失败，请重试",
    verificationTitle: "验收结果",
    verifyPass: "全部通过",
    verifyFail: "存在未通过项",
    emptyTitle: "内容配方会出现在这里",
    emptyBody: "配方记录这次内容是如何生成的，下次可以换输入重跑。",
    summaryName: "配方名称",
    summaryIntent: "内容类型",
    summaryAudience: "目标受众",
    summaryGoal: "内容目标",
    summaryTone: "语气风格",
    summaryVisual: "视觉规范",
    summaryStructure: "结构方式",
    summaryNegative: "禁止项",
    summaryVariables: "可替换变量",
    summaryAcceptance: "验收标准",
  },
  assumptions: {
    title: "内容假设",
    hint: "这些是系统对你想法的理解。点击可编辑，× 可删除，改完点「应用并重新生成」。",
    regenerate: "应用修改并重新生成",
    edited: "已改",
    fromProfile: "来自偏好",
    remembered: "已记住",
    rememberTitle: "记住为偏好，下次自动带出",
    editTitle: "点击编辑",
    restoreTitle: "点击恢复",
    allDismissed: "已删除全部假设，系统将仅依据原始输入生成。",
    dismissedLabel: "已删除假设（{n}）",
    restoreAll: "恢复全部",
    editAria: "编辑 {label}",
    rememberAria: "把「{label}」记住为偏好",
    dismissAria: "删除假设 {label}",
  },
  performance: {
    expand: "记录发布表现",
    title: "记录发布表现",
    subtitle: "手动回填，仅你可见，不自动抓取",
    unfilled: "未填",
    rangeSuffix: "区间",
    publishedAt: "发布时间（可选）",
    note: "一句话复盘（可选）",
    notePlaceholder: "例如：收藏比点赞高，干货向有效",
    save: "保存表现",
    saving: "保存中…",
    saved: "已记录表现",
    failed: "回填失败，请重试",
    like: "点赞",
    favorite: "收藏",
    comment: "评论",
    follower: "涨粉",
  },
  recipes: {
    title: "配方库",
    description: "查看、搜索、筛选和删除已保存的内容配方。",
    newRecipe: "新建配方",
    searchAria: "搜索配方名称",
    searchPlaceholder: "按配方名称搜索",
    filterAria: "内容类型筛选",
    search: "搜索",
    filtering: "筛选中…",
    clear: "清空",
    showing: "当前显示 {n} 条",
    ofTotal: " / 全部 {n} 条",
    loadingResults: "正在加载筛选结果…",
    deleted: "已删除配方",
    deleteFailed: "删除失败，请重试",
    createdAt: "创建时间",
    updatedAt: "更新时间",
    usageCount: "使用次数",
    sourceSession: "来源 session",
    noSource: "无来源 session",
    viewDetail: "查看详情",
    emptyFilteredTitle: "没有符合条件的配方",
    emptyTitle: "还没有配方",
    emptyFilteredBody: "换个关键词或内容类型再试。",
    emptyBody: "在 Forge 工作台生成内容后，把好用的内容配方保存到这里。",
    goCreate: "去 Forge 创建",
  },
  recipeDetail: {
    backToLibrary: "返回配方库",
    fieldsTitle: "配方字段",
    rerunTitle: "换输入重跑",
    notFoundTitle: "配方不存在或不可见",
    notFoundBody: "这条配方可能已被删除，或不属于当前账号。",
    backToLibraryBtn: "回到配方库",
    createdAt: "创建时间",
    updatedAt: "更新时间",
    usageCount: "使用次数",
    sourceSession: "来源 session",
    noSource: "无来源 session",
    audience: "目标受众",
    goal: "内容目标",
    tone: "语气风格",
    visualStyle: "视觉规范",
    structure: "结构方式",
    variables: "可替换变量",
    negativeRules: "禁止项",
    acceptance: "验收标准",
    schema: "版本",
    rerunDescription: "沿用本配方，输入一个新主题，生成一个新的结果。原配方不会被改动。",
    rerunPlaceholder: "写下新的主题，例如：想做一组退租拍照清单的图文卡片",
    rerunButton: "换输入重跑",
    rerunning: "重跑中…",
    charCounter: "{count} / {max} 字",
    overLimitSuffix: "（已超出上限）",
    rerunFailed: "重跑失败，请重试",
  },
  profile: {
    title: "偏好",
    description:
      "记住你常用的内容假设（受众、语气、视觉风格等）。下次在 Forge 生成时会自动作为假设带出，可随时编辑或删除。",
    addTitle: "新增偏好",
    intentTypeAria: "内容类型",
    dimensionLabelPlaceholder: "维度名，如：语气",
    dimensionKeyPlaceholder: "维度 key，如：tone",
    add: "添加",
    valuePlaceholder: "偏好值，如：成熟、克制、不焦虑",
    addHint:
      "同一「内容类型 + 维度 key」重复添加会覆盖旧值。下次 Forge 生成时作为「来自偏好」假设带出。",
    count: "共 {n} 条偏好",
    refreshing: "正在刷新…",
    savedPref: "已保存偏好",
    updatedPref: "已更新偏好",
    deletedPref: "已删除偏好",
    saveFailed: "保存失败，请重试",
    editFailed: "修改失败，请重试",
    deleteFailed: "删除失败，请重试",
    editValueAria: "编辑 {label} 的值",
    updatedAt: "更新于 {date}",
    emptyTitle: "还没有偏好",
    emptyBody:
      "在上方添加常用的内容假设，或在 Forge 工作台编辑假设后点「记住为偏好」。下次生成会自动带出。",
  },
};

/** copy 的规范结构（key 固定、值为 string）。`en` 必须实现同一组 key。 */
export type Copy = typeof zhHans;
