// ForgeNote M2 — UI copy 资源（zh-Hans，**规范源**）。
//
// 设计：
//   - 本文件是 copy 的**唯一规范结构**与默认语言；值为当前线上中文文案，逐字迁移、不改产品含义。
//   - `Copy = typeof zhHans`（不使用 `as const`，值类型收敛为 string）→ `en` 必须实现同一组 key，
//     从而在编译期保证两套 copy **key 不漂移**（缺 key / 多 key / 改 key 都会类型报错）。
//   - 仅 scaffold：不引入 i18n 运行时 / 不做语言切换 / 默认仍 zh-Hans，行为不变。
//   - 含 `{n}` / `{max}` / `{label}` / `{date}` 占位符的值，由调用处 `.replace(...)` 注入。
//   - 已在 `constants.ts` 集中的产品级文案（PRODUCT_NAME / SLOGAN / POSITIONING / 示例想法 / 输入占位）
//     不在此重复，避免双源漂移。

export const zhHans = {
  common: {
    cancel: "取消",
    save: "保存",
    saving: "保存中…",
    edit: "编辑",
    delete: "删除",
    confirmDeletePrompt: "确认删除？",
    confirmDelete: "确认删除",
    deleting: "删除中…",
    copied: "已复制",
    networkError: "网络异常，请稍后重试",
    optionalSuffix: "（可选）",
  },
  nav: {
    profile: "偏好",
    signOut: "退出",
    signOutTitle: "退出登录",
  },
  intentTypes: {
    content_package: "内容方案",
    xiaohongshu_note: "图文笔记",
    card_prompt: "画面说明",
    generic_content: "通用内容",
    all: "全部类型",
  },
  login: {
    categoryLine: "图文卡片内容工作台",
    signinTitle: "欢迎回来",
    signinSubtitle: "输入邮箱和密码，继续锻造你的内容",
    signupTitle: "创建账号",
    signupSubtitle: "填邮箱和密码，开始使用 ForgeNote",
    emailLabel: "邮箱地址",
    emailPlaceholder: "you@example.com",
    passwordLabel: "密码",
    passwordPlaceholder: "输入密码",
    passwordPlaceholderSignup: "设置密码（至少 8 位）",
    confirmPasswordLabel: "确认密码",
    confirmPasswordPlaceholder: "确认密码",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
    rememberFor30Days: "保持 30 天登录",
    forgotPassword: "忘记密码？",
    submit: "登录",
    submitting: "登录中…",
    signupSubmit: "创建账号",
    google: "使用 Google 登录",
    googleRedirecting: "正在跳转到 Google…",
    orDivider: "或",
    noAccountPrompt: "还没有账号？",
    toSignUpLink: "创建账号",
    hasAccountPrompt: "已有账号？",
    toSignInLink: "返回登录",
    invalidCredentials: "邮箱或密码不正确，请检查后重试。",
    emailNotConfirmed: "这个邮箱还没确认。请先点一次确认邮件，之后可用密码直接登录。",
    authNeedsCheck: "登录未完成。请检查邮箱、密码，或先打开确认邮件。",
    authFailed: "登录失败，请稍后重试。",
    networkError: "登录失败，请检查网络后重试。",
    googleUnavailable: "Google 登录暂不可用，请改用邮箱和密码登录。",
    googleInitFailed: "无法发起 Google 登录，请稍后重试或改用邮箱登录。",
    signupSentTitle: "确认邮件已发送",
    signupSentBodyPrefix: "我们已向 ",
    signupSentBodySuffix:
      " 发送确认邮件。首次点一次确认即可，之后用邮箱和密码直接登录。",
    changeEmail: "换一个邮箱",
    notConfiguredTitle: "登录暂不可用：Supabase 未配置",
    notConfiguredBody:
      "缺少 NEXT_PUBLIC_SUPABASE_URL 或 NEXT_PUBLIC_SUPABASE_ANON_KEY，请在环境变量中配置后重试。",
  },
  reset: {
    requestTitle: "重置密码",
    requestSubtitle: "输入注册邮箱，我们会发一封重置链接给你",
    submit: "发送重置邮件",
    submitting: "发送中…",
    backToSignIn: "← 返回登录",
    sentTitle: "重置邮件已发送",
    sentBodyPrefix: "我们已向 ",
    sentBodySuffix: " 发送重置链接。打开邮件点链接，即可设置新密码。",
    resend: "没收到？重新发送",
    resendIn: "{seconds} 秒后可重新发送",
    cooldownHint: "请先查看最新邮件。为避免重复邮件，{seconds} 秒后可重新发送。",
    canResendHint: "如果仍没收到，可以重新发送一封新的重置邮件。",
    newTitle: "设置新密码",
    newSubtitle: "给账号设置一个新密码（至少 8 位）",
    newPasswordPlaceholder: "新密码（至少 8 位）",
    confirmPasswordPlaceholder: "再输入一次新密码",
    saveNewPassword: "保存新密码",
    saving: "保存中…",
    passwordMismatch: "两次输入的新密码不一致。",
    sendFailed: "发送没有完成。请先查看最新邮件，稍后再重新发送。",
    updateFailed: "重置失败，请重新发起找回。",
    networkError: "操作失败，请检查网络后重试。",
    linkInvalid: "重置链接无效或已过期，请重新发起找回。",
    doneTitle: "密码已更新",
    doneBody: "新密码设置成功，现在可以用它登录了。",
    goSignIn: "去登录",
  },
  performance: {
    expand: "记录发布表现",
    title: "记录发布表现",
    subtitle: "手动回填，仅你可见，不自动抓取",
    unfilled: "未填",
    rangeSuffix: "区间",
    publishedAt: "发布时间（可选）",
    note: "一句话复盘（可选）",
    notePlaceholder: "例如：收藏比点赞高，干货向有效",
    save: "保存表现",
    saving: "保存中…",
    saved: "已记录表现",
    failed: "回填失败，请重试",
    like: "点赞",
    favorite: "收藏",
    comment: "评论",
    follower: "涨粉",
  },
  profile: {
    title: "偏好",
    description:
      "记住你常用的内容假设（受众、语气、视觉风格等）。下次在工作台生成时会自动作为假设带出，可随时编辑或删除。",
    addTitle: "新增偏好",
    intentTypeAria: "内容类型",
    dimensionLabelPlaceholder: "维度名，如：语气",
    dimensionKeyPlaceholder: "维度 key，如：tone",
    add: "添加",
    valuePlaceholder: "偏好值，如：成熟、克制、不焦虑",
    addHint:
      "同一「内容类型 + 维度 key」重复添加会覆盖旧值。下次工作台生成时作为「来自偏好」假设带出。",
    count: "共 {n} 条偏好",
    refreshing: "正在刷新…",
    savedPref: "已保存偏好",
    updatedPref: "已更新偏好",
    deletedPref: "已删除偏好",
    saveFailed: "保存失败，请重试",
    editFailed: "修改失败，请重试",
    deleteFailed: "删除失败，请重试",
    editValueAria: "编辑 {label} 的值",
    updatedAt: "更新于 {date}",
    emptyTitle: "还没有偏好",
    emptyBody:
      "在上方添加常用的内容假设，或在工作台编辑假设后点「记住为偏好」。下次生成会自动带出。",
  },
};

/** copy 的规范结构（key 固定、值为 string）。`en` 必须实现同一组 key。 */
export type Copy = typeof zhHans;
